version: "3.9"

services:
  idurar-frontend-jenkins:
    image: node:18-alpine
    container_name: idurar-frontend-jenkins
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npx serve -s dist -l 5174"
    ports:
      - "5174:5174"

  idurar-backend-jenkins:
    image: node:18-alpine
    container_name: idurar-backend-jenkins
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      MONGO_URL: "mongodb://idurar-mongo-jenkins:27017/idurar_db"
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"
    depends_on:
      - idurar-mongo-jenkins

  idurar-mongo-jenkins:
    image: mongo:5
    container_name: idurar-mongo-jenkins
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
